#!/bin/bash
# Assemble a signed apt repository from a directory of .debs.
#
# The output is a plain static tree — no server-side software — so it can be
# published to GitHub Pages, copied to an nginx docroot, or rsync'd to a lab
# server for rigs with no internet access. All three are the same bytes.
#
#   packaging/apt/build-repo.sh <deb-dir> <out-dir>
#
# Environment:
#   SUITE            apt suite to publish into (default: stable)
#   ORIGIN / LABEL   Release file metadata (default: braemons / vstimd)
#   APT_SIGNING_KEY  ASCII-armored private key. Unset means an unsigned repo,
#                    which apt only accepts with [trusted=yes] — fine for a
#                    local test, not for anything a rig points at.
#
# Run via `make apt-repo`, which executes this inside a Debian container so the
# apt-ftparchive version matches what the rigs consume.
set -euo pipefail

DEB_DIR=${1:?usage: build-repo.sh <deb-dir> <out-dir>}
OUT_DIR=${2:?usage: build-repo.sh <deb-dir> <out-dir>}

SUITE=${SUITE:-stable}
ORIGIN=${ORIGIN:-braemons}
LABEL=${LABEL:-vstimd}
# The architectures the rigs actually run. amd64 is here for desktop/test rigs;
# the Raspberry Pi and Jetson deployments are arm64.
ARCHES=${ARCHES:-amd64 arm64}

shopt -s nullglob
debs=("$DEB_DIR"/*.deb)
if [ ${#debs[@]} -eq 0 ]; then
    echo "build-repo.sh: no .deb files in $DEB_DIR" >&2
    exit 1
fi

echo "==> publishing ${#debs[@]} package(s) into suite '$SUITE'"

# ── Pool ──────────────────────────────────────────────────────────────────────
# pool/<suite>/main/<first-letter>/<package>/<file>.deb.
#
# Debian shares one pool across suites, but the index is generated by scanning
# a directory: a shared pool would put every alpha into the 'stable' Packages
# file, which is the opposite of why the suites are split. One pool per suite
# keeps them genuinely independent.
#
# Existing files are left in place, so a suite accumulates its published
# versions and a rig can pin or roll back to an earlier one.
POOL="pool/$SUITE/main"
for deb in "${debs[@]}"; do
    pkg=$(dpkg-deb -f "$deb" Package)
    letter=${pkg:0:1}
    dest="$OUT_DIR/$POOL/$letter/$pkg"
    mkdir -p "$dest"
    cp -f "$deb" "$dest/"
    echo "    $POOL/$letter/$pkg/$(basename "$deb")"
done

# ── Per-architecture package indices ─────────────────────────────────────────
for arch in $ARCHES; do
    dir="$OUT_DIR/dists/$SUITE/main/binary-$arch"
    mkdir -p "$dir"
    # Paths inside Packages must be relative to the repo root, so scan from there.
    ( cd "$OUT_DIR" && apt-ftparchive --arch "$arch" packages "$POOL" ) > "$dir/Packages"
    gzip -9kf "$dir/Packages"
    count=$(grep -c '^Package: ' "$dir/Packages" || true)
    echo "    dists/$SUITE/main/binary-$arch: $count package(s)"

    # apt fails a suite outright if a declared architecture has no index at all,
    # so an empty Packages file is correct and must still be published.
done

# ── Release ───────────────────────────────────────────────────────────────────
release_conf=$(mktemp)
cat > "$release_conf" <<EOF
APT::FTPArchive::Release::Origin "$ORIGIN";
APT::FTPArchive::Release::Label "$LABEL";
APT::FTPArchive::Release::Suite "$SUITE";
APT::FTPArchive::Release::Codename "$SUITE";
APT::FTPArchive::Release::Architectures "$ARCHES";
APT::FTPArchive::Release::Components "main";
APT::FTPArchive::Release::Description "vstimd packages ($SUITE)";
EOF

( cd "$OUT_DIR" && apt-ftparchive -c "$release_conf" release "dists/$SUITE" ) \
    > "$OUT_DIR/dists/$SUITE/Release"
rm -f "$release_conf"

# ── Signature ─────────────────────────────────────────────────────────────────
if [ -n "${APT_SIGNING_KEY:-}" ]; then
    export GNUPGHOME
    GNUPGHOME=$(mktemp -d)
    chmod 700 "$GNUPGHOME"
    printf '%s' "$APT_SIGNING_KEY" | gpg --batch --quiet --import

    keyid=$(gpg --batch --with-colons --list-secret-keys \
            | awk -F: '/^sec:/ {print $5; exit}')
    [ -n "$keyid" ] || { echo "build-repo.sh: no secret key found in APT_SIGNING_KEY" >&2; exit 1; }

    rel="$OUT_DIR/dists/$SUITE/Release"
    # Both forms: InRelease is what modern apt fetches, Release.gpg keeps older
    # clients and mirroring tools working.
    gpg --batch --yes --local-user "$keyid" --armor --detach-sign \
        --output "$rel.gpg" "$rel"
    gpg --batch --yes --local-user "$keyid" --clearsign \
        --output "$OUT_DIR/dists/$SUITE/InRelease" "$rel"

    # Ship the public key beside the repo so a rig can bootstrap trust from the
    # same URL it installs from.
    gpg --batch --yes --armor --export "$keyid" > "$OUT_DIR/braemons-archive-keyring.asc"

    rm -rf "$GNUPGHOME"
    echo "==> signed with $keyid"
else
    echo "WARNING: APT_SIGNING_KEY is unset — this repository is UNSIGNED." >&2
    echo "         apt will refuse it unless the source says [trusted=yes]." >&2
    echo "         Acceptable for a local test; never for a repo rigs point at." >&2
fi

echo "==> repository written to $OUT_DIR"
