# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: vstimd/v1/stimuli/ellipse.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'vstimd/v1/stimuli/ellipse.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from vstimd_client._proto.vstimd.v1.stimuli import identity_pb2 as vstimd_dot_v1_dot_stimuli_dot_identity__pb2
from vstimd_client._proto.vstimd.v1.stimuli import shapes_pb2 as vstimd_dot_v1_dot_stimuli_dot_shapes__pb2
from vstimd_client._proto.vstimd.v1 import transform_pb2 as vstimd_dot_v1_dot_transform__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fvstimd/v1/stimuli/ellipse.proto\x12\tvstimd.v1\x1a vstimd/v1/stimuli/identity.proto\x1a\x1evstimd/v1/stimuli/shapes.proto\x1a\x19vstimd/v1/transform.proto\"\x9a\x01\n\x14\x43reateEllipseRequest\x12-\n\x08identity\x18\x01 \x01(\x0b\x32\x1b.vstimd.v1.StimulusIdentity\x12)\n\tplacement\x18\x02 \x01(\x0b\x32\x16.vstimd.v1.Transform2D\x12(\n\x06params\x18\x03 \x01(\x0b\x32\x18.vstimd.v1.EllipseParams\"<\n\x15SetEllipseSizeRequest\x12\x10\n\x08width_px\x18\x01 \x01(\x02\x12\x11\n\theight_px\x18\x02 \x01(\x02\"d\n\rEllipseParams\x12\x10\n\x08width_px\x18\x01 \x01(\x02\x12\x11\n\theight_px\x18\x02 \x01(\x02\x12.\n\nappearance\x18\x03 \x01(\x0b\x32\x1a.vstimd.v1.ShapeAppearanceb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'vstimd.v1.stimuli.ellipse_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CREATEELLIPSEREQUEST']._serialized_start=140
  _globals['_CREATEELLIPSEREQUEST']._serialized_end=294
  _globals['_SETELLIPSESIZEREQUEST']._serialized_start=296
  _globals['_SETELLIPSESIZEREQUEST']._serialized_end=356
  _globals['_ELLIPSEPARAMS']._serialized_start=358
  _globals['_ELLIPSEPARAMS']._serialized_end=458
# @@protoc_insertion_point(module_scope)
