# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: vstimd/v1/stimuli/rect.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'vstimd/v1/stimuli/rect.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from vstimd_client._proto.vstimd.v1.stimuli import identity_pb2 as vstimd_dot_v1_dot_stimuli_dot_identity__pb2
from vstimd_client._proto.vstimd.v1.stimuli import shapes_pb2 as vstimd_dot_v1_dot_stimuli_dot_shapes__pb2
from vstimd_client._proto.vstimd.v1 import transform_pb2 as vstimd_dot_v1_dot_transform__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cvstimd/v1/stimuli/rect.proto\x12\tvstimd.v1\x1a vstimd/v1/stimuli/identity.proto\x1a\x1evstimd/v1/stimuli/shapes.proto\x1a\x19vstimd/v1/transform.proto\"\x94\x01\n\x11\x43reateRectRequest\x12-\n\x08identity\x18\x01 \x01(\x0b\x32\x1b.vstimd.v1.StimulusIdentity\x12)\n\tplacement\x18\x02 \x01(\x0b\x32\x16.vstimd.v1.Transform2D\x12%\n\x06params\x18\x03 \x01(\x0b\x32\x15.vstimd.v1.RectParams\"9\n\x12SetRectSizeRequest\x12\x10\n\x08width_px\x18\x01 \x01(\x02\x12\x11\n\theight_px\x18\x02 \x01(\x02\"a\n\nRectParams\x12\x10\n\x08width_px\x18\x01 \x01(\x02\x12\x11\n\theight_px\x18\x02 \x01(\x02\x12.\n\nappearance\x18\x03 \x01(\x0b\x32\x1a.vstimd.v1.ShapeAppearanceb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'vstimd.v1.stimuli.rect_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CREATERECTREQUEST']._serialized_start=137
  _globals['_CREATERECTREQUEST']._serialized_end=285
  _globals['_SETRECTSIZEREQUEST']._serialized_start=287
  _globals['_SETRECTSIZEREQUEST']._serialized_end=344
  _globals['_RECTPARAMS']._serialized_start=346
  _globals['_RECTPARAMS']._serialized_end=443
# @@protoc_insertion_point(module_scope)
