# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: vstimd/v1/stimuli/shapes.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'vstimd/v1/stimuli/shapes.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from vstimd_client._proto.vstimd.v1 import color_pb2 as vstimd_dot_v1_dot_color__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1evstimd/v1/stimuli/shapes.proto\x12\tvstimd.v1\x1a\x15vstimd/v1/color.proto\"<\n\x12SetDrawModeRequest\x12&\n\x04mode\x18\x01 \x01(\x0e\x32\x18.vstimd.v1.ShapeDrawMode\"\xa7\x01\n\x0fShapeAppearance\x12$\n\nfill_color\x18\x01 \x01(\x0b\x32\x10.vstimd.v1.Color\x12\'\n\routline_color\x18\x02 \x01(\x0b\x32\x10.vstimd.v1.Color\x12\x18\n\x10outline_width_px\x18\x03 \x01(\x02\x12+\n\tdraw_mode\x18\x04 \x01(\x0e\x32\x18.vstimd.v1.ShapeDrawMode\"9\n\x16SetOutlineColorRequest\x12\x1f\n\x05\x63olor\x18\x01 \x01(\x0b\x32\x10.vstimd.v1.Color\"/\n\x16SetOutlineWidthRequest\x12\x15\n\rline_width_px\x18\x01 \x01(\x02*\x93\x01\n\rShapeDrawMode\x12\x1f\n\x1bSHAPE_DRAW_MODE_UNSPECIFIED\x10\x00\x12\x1a\n\x16SHAPE_DRAW_MODE_FILLED\x10\x01\x12\x1c\n\x18SHAPE_DRAW_MODE_OUTLINED\x10\x02\x12\'\n#SHAPE_DRAW_MODE_FILLED_AND_OUTLINED\x10\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'vstimd.v1.stimuli.shapes_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SHAPEDRAWMODE']._serialized_start=409
  _globals['_SHAPEDRAWMODE']._serialized_end=556
  _globals['_SETDRAWMODEREQUEST']._serialized_start=68
  _globals['_SETDRAWMODEREQUEST']._serialized_end=128
  _globals['_SHAPEAPPEARANCE']._serialized_start=131
  _globals['_SHAPEAPPEARANCE']._serialized_end=298
  _globals['_SETOUTLINECOLORREQUEST']._serialized_start=300
  _globals['_SETOUTLINECOLORREQUEST']._serialized_end=357
  _globals['_SETOUTLINEWIDTHREQUEST']._serialized_start=359
  _globals['_SETOUTLINEWIDTHREQUEST']._serialized_end=406
# @@protoc_insertion_point(module_scope)
