# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: vstimd/v1/stimuli/shared_set_requests.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'vstimd/v1/stimuli/shared_set_requests.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from vstimd_client._proto.vstimd.v1 import color_pb2 as vstimd_dot_v1_dot_color__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n+vstimd/v1/stimuli/shared_set_requests.proto\x12\tvstimd.v1\x1a\x15vstimd/v1/color.proto\"$\n\x11SetEnabledRequest\x12\x0f\n\x07\x65nabled\x18\x01 \x01(\x08\"\x0f\n\rDeleteRequest\"\x1e\n\x0eSetNameRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"0\n\x12SetPositionRequest\x12\x0c\n\x04x_px\x18\x01 \x01(\x02\x12\x0c\n\x04y_px\x18\x02 \x01(\x02\"*\n\x12SetRotationRequest\x12\x14\n\x0crotation_deg\x18\x01 \x01(\x02\"6\n\x13SetFillColorRequest\x12\x1f\n\x05\x63olor\x18\x01 \x01(\x0b\x32\x10.vstimd.v1.Color\"\"\n\x0fSetAlphaRequest\x12\x0f\n\x07opacity\x18\x01 \x01(\x02\"\x15\n\x13\x42ringToFrontRequest\"\x13\n\x11SendToBackRequest\":\n\x14SwapDrawOrderRequest\x12\x10\n\x08handle_a\x18\x01 \x01(\r\x12\x10\n\x08handle_b\x18\x02 \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'vstimd.v1.stimuli.shared_set_requests_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SETENABLEDREQUEST']._serialized_start=81
  _globals['_SETENABLEDREQUEST']._serialized_end=117
  _globals['_DELETEREQUEST']._serialized_start=119
  _globals['_DELETEREQUEST']._serialized_end=134
  _globals['_SETNAMEREQUEST']._serialized_start=136
  _globals['_SETNAMEREQUEST']._serialized_end=166
  _globals['_SETPOSITIONREQUEST']._serialized_start=168
  _globals['_SETPOSITIONREQUEST']._serialized_end=216
  _globals['_SETROTATIONREQUEST']._serialized_start=218
  _globals['_SETROTATIONREQUEST']._serialized_end=260
  _globals['_SETFILLCOLORREQUEST']._serialized_start=262
  _globals['_SETFILLCOLORREQUEST']._serialized_end=316
  _globals['_SETALPHAREQUEST']._serialized_start=318
  _globals['_SETALPHAREQUEST']._serialized_end=352
  _globals['_BRINGTOFRONTREQUEST']._serialized_start=354
  _globals['_BRINGTOFRONTREQUEST']._serialized_end=375
  _globals['_SENDTOBACKREQUEST']._serialized_start=377
  _globals['_SENDTOBACKREQUEST']._serialized_end=396
  _globals['_SWAPDRAWORDERREQUEST']._serialized_start=398
  _globals['_SWAPDRAWORDERREQUEST']._serialized_end=456
# @@protoc_insertion_point(module_scope)
