# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: vstimd/v1/stimuli/stimulus_type.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'vstimd/v1/stimuli/stimulus_type.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%vstimd/v1/stimuli/stimulus_type.proto\x12\tvstimd.v1*\xc8\x03\n\x0cStimulusType\x12\x1d\n\x19STIMULUS_TYPE_UNSPECIFIED\x10\x00\x12\x16\n\x12STIMULUS_TYPE_RECT\x10\x01\x12\x18\n\x14STIMULUS_TYPE_CIRCLE\x10\x02\x12\x19\n\x15STIMULUS_TYPE_ELLIPSE\x10\x03\x12\x18\n\x14STIMULUS_TYPE_BITMAP\x10\x07\x12\x18\n\x14STIMULUS_TYPE_SHADER\x10\x08\x12\x1a\n\x16STIMULUS_TYPE_PARTICLE\x10\t\x12\x19\n\x15STIMULUS_TYPE_GRATING\x10\n\x12\x16\n\x12STIMULUS_TYPE_TEXT\x10\x0b\x12\x19\n\x15STIMULUS_TYPE_POLYGON\x10\x0c\x12\x16\n\x12STIMULUS_TYPE_DOTS\x10\r\x12\x19\n\x15STIMULUS_TYPE_CUBE_3D\x10\x14\x12\x1b\n\x17STIMULUS_TYPE_SPHERE_3D\x10\x15\x12\x1a\n\x16STIMULUS_TYPE_PLANE_3D\x10\x16\x12\x1d\n\x19STIMULUS_TYPE_CORRIDOR_3D\x10\x17\x12#\n\x1fSTIMULUS_TYPE_GAUSSIAN_SPLAT_3D\x10\x18\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'vstimd.v1.stimuli.stimulus_type_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STIMULUSTYPE']._serialized_start=53
  _globals['_STIMULUSTYPE']._serialized_end=509
# @@protoc_insertion_point(module_scope)
