# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: vstimd/v1/stimuli/text.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'vstimd/v1/stimuli/text.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from vstimd_client._proto.vstimd.v1 import vec2_pb2 as vstimd_dot_v1_dot_vec2__pb2
from vstimd_client._proto.vstimd.v1 import color_pb2 as vstimd_dot_v1_dot_color__pb2
from vstimd_client._proto.vstimd.v1.stimuli import identity_pb2 as vstimd_dot_v1_dot_stimuli_dot_identity__pb2
from vstimd_client._proto.vstimd.v1 import transform_pb2 as vstimd_dot_v1_dot_transform__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cvstimd/v1/stimuli/text.proto\x12\tvstimd.v1\x1a\x14vstimd/v1/vec2.proto\x1a\x15vstimd/v1/color.proto\x1a vstimd/v1/stimuli/identity.proto\x1a\x19vstimd/v1/transform.proto\"\x94\x01\n\x11\x43reateTextRequest\x12-\n\x08identity\x18\x01 \x01(\x0b\x32\x1b.vstimd.v1.StimulusIdentity\x12)\n\tplacement\x18\x02 \x01(\x0b\x32\x16.vstimd.v1.Transform2D\x12%\n\x06params\x18\x03 \x01(\x0b\x32\x15.vstimd.v1.TextParams\"\x1e\n\x0eSetTextRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\"6\n\x13SetTextColorRequest\x12\x1f\n\x05\x63olor\x18\x01 \x01(\x0b\x32\x10.vstimd.v1.Color\"\xb2\x02\n\nTextParams\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x0c\n\x04\x66ont\x18\x02 \x01(\t\x12\x18\n\x10letter_height_px\x18\x03 \x01(\x02\x12$\n\x0b\x62ox_size_px\x18\x04 \x01(\x0b\x32\x0f.vstimd.v1.Vec2\x12\x0e\n\x06\x61nchor\x18\x05 \x01(\t\x12$\n\nfill_color\x18\x06 \x01(\x0b\x32\x10.vstimd.v1.Color\x12&\n\x0c\x62order_color\x18\x07 \x01(\x0b\x32\x10.vstimd.v1.Color\x12\x12\n\nflip_horiz\x18\x08 \x01(\x08\x12\x30\n\x0elanguage_style\x18\t \x01(\x0e\x32\x18.vstimd.v1.LanguageStyle\x12$\n\ntext_color\x18\n \x01(\x0b\x32\x10.vstimd.v1.Color*z\n\rLanguageStyle\x12\x1e\n\x1aLANGUAGE_STYLE_UNSPECIFIED\x10\x00\x12\x16\n\x12LANGUAGE_STYLE_LTR\x10\x01\x12\x16\n\x12LANGUAGE_STYLE_RTL\x10\x02\x12\x19\n\x15LANGUAGE_STYLE_ARABIC\x10\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'vstimd.v1.stimuli.text_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LANGUAGESTYLE']._serialized_start=697
  _globals['_LANGUAGESTYLE']._serialized_end=819
  _globals['_CREATETEXTREQUEST']._serialized_start=150
  _globals['_CREATETEXTREQUEST']._serialized_end=298
  _globals['_SETTEXTREQUEST']._serialized_start=300
  _globals['_SETTEXTREQUEST']._serialized_end=330
  _globals['_SETTEXTCOLORREQUEST']._serialized_start=332
  _globals['_SETTEXTCOLORREQUEST']._serialized_end=386
  _globals['_TEXTPARAMS']._serialized_start=389
  _globals['_TEXTPARAMS']._serialized_end=695
# @@protoc_insertion_point(module_scope)
