"""Automated API compatibility check: vstim_client.visual vs psychopy.visual.

This file uses fixtures generated by ``compat/check_compat.py --output-pytest-fixtures``.
If the fixtures file doesn't exist yet, tests are skipped automatically.

Run the compat check to regenerate:
    python compat/check_compat.py --output-pytest-fixtures tests/_compat_fixtures.py
"""

from __future__ import annotations

import importlib
import inspect

import pytest

from vstim_client import visual as vstim_visual

# Try to load generated fixtures; if absent, skip all compat tests.
try:
    from tests._compat_fixtures import CHECKED_CLASSES, REQUIRED_PARAMS, ALL_METHODS  # type: ignore[import]
    _HAS_FIXTURES = True
except ImportError:
    _HAS_FIXTURES = False
    CHECKED_CLASSES = []
    REQUIRED_PARAMS = []
    ALL_METHODS = []

pytestmark = pytest.mark.skipif(
    not _HAS_FIXTURES,
    reason="No compat fixtures found. Run: python compat/check_compat.py --output-pytest-fixtures tests/_compat_fixtures.py",
)


@pytest.mark.parametrize("class_name", CHECKED_CLASSES)
def test_class_exists(class_name: str) -> None:
    assert hasattr(vstim_visual, class_name), (
        f"vstim_client.visual is missing class: {class_name}"
    )


@pytest.mark.parametrize("class_name,method", ALL_METHODS)
def test_method_exists(class_name: str, method: str) -> None:
    cls = getattr(vstim_visual, class_name, None)
    assert cls is not None, f"Class {class_name} not found"
    assert hasattr(cls, method), (
        f"{class_name}.{method}() is missing from vstim_client.visual"
    )


@pytest.mark.parametrize("class_name,param", REQUIRED_PARAMS)
def test_init_param_exists(class_name: str, param: str) -> None:
    cls = getattr(vstim_visual, class_name, None)
    assert cls is not None, f"Class {class_name} not found"
    sig = inspect.signature(cls.__init__)
    assert param in sig.parameters, (
        f"{class_name}.__init__ is missing parameter: {param}"
    )
