# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: vstimd/v1/conditions.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'vstimd/v1/conditions.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1avstimd/v1/conditions.proto\x12\tvstimd.v1\"(\n\tCondition\x12\r\n\x05index\x18\x01 \x01(\r\x12\x0c\n\x04name\x18\x02 \x01(\t\"C\n\x13SetConditionRequest\x12\x0f\n\x05index\x18\x01 \x01(\rH\x00\x12\x0e\n\x04name\x18\x02 \x01(\tH\x00\x42\x0b\n\tcondition\"D\n\x18\x44\x65\x63lareConditionsRequest\x12(\n\nconditions\x18\x01 \x03(\x0b\x32\x14.vstimd.v1.Condition\"\x17\n\x15ListConditionsRequest\"m\n\x16ListConditionsResponse\x12(\n\nconditions\x18\x01 \x03(\x0b\x32\x14.vstimd.v1.Condition\x12\x14\n\x0c\x61\x63tive_index\x18\x02 \x01(\r\x12\x13\n\x0b\x61\x63tive_name\x18\x03 \x01(\t\"9\n\x1cSetStimulusConditionsRequest\x12\x19\n\x11\x63ondition_indices\x18\x01 \x03(\r\"\x80\x01\n\x1dSetAnimationConditionsRequest\x12\x0e\n\x06handle\x18\x01 \x01(\r\x12\x19\n\x11\x63ondition_indices\x18\x02 \x03(\r\x12\x34\n\x10\x63ondition_action\x18\x03 \x01(\x0e\x32\x1a.vstimd.v1.ConditionAction*\x85\x01\n\x0f\x43onditionAction\x12 \n\x1c\x43ONDITION_ACTION_UNSPECIFIED\x10\x00\x12\x1a\n\x16\x43ONDITION_ACTION_RESET\x10\x01\x12\x19\n\x15\x43ONDITION_ACTION_HOLD\x10\x02\x12\x19\n\x15\x43ONDITION_ACTION_STOP\x10\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'vstimd.v1.conditions_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CONDITIONACTION']._serialized_start=549
  _globals['_CONDITIONACTION']._serialized_end=682
  _globals['_CONDITION']._serialized_start=41
  _globals['_CONDITION']._serialized_end=81
  _globals['_SETCONDITIONREQUEST']._serialized_start=83
  _globals['_SETCONDITIONREQUEST']._serialized_end=150
  _globals['_DECLARECONDITIONSREQUEST']._serialized_start=152
  _globals['_DECLARECONDITIONSREQUEST']._serialized_end=220
  _globals['_LISTCONDITIONSREQUEST']._serialized_start=222
  _globals['_LISTCONDITIONSREQUEST']._serialized_end=245
  _globals['_LISTCONDITIONSRESPONSE']._serialized_start=247
  _globals['_LISTCONDITIONSRESPONSE']._serialized_end=356
  _globals['_SETSTIMULUSCONDITIONSREQUEST']._serialized_start=358
  _globals['_SETSTIMULUSCONDITIONSREQUEST']._serialized_end=415
  _globals['_SETANIMATIONCONDITIONSREQUEST']._serialized_start=418
  _globals['_SETANIMATIONCONDITIONSREQUEST']._serialized_end=546
# @@protoc_insertion_point(module_scope)
