# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: vstimd/v1/events.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'vstimd/v1/events.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from vstimd_client._proto.vstimd.v1 import vtl_pb2 as vstimd_dot_v1_dot_vtl__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16vstimd/v1/events.proto\x12\tvstimd.v1\x1a\x13vstimd/v1/vtl.proto\"\xbe\x03\n\x05\x45vent\x12\x10\n\x08sequence\x18\x01 \x01(\x04\x12\x16\n\x0etopic_sequence\x18\x05 \x01(\x04\x12\x14\n\x0cmonotonic_us\x18\x02 \x01(\x04\x12\r\n\x05\x66rame\x18\x04 \x01(\x04\x12\r\n\x05topic\x18\x03 \x01(\t\x12\x30\n\rframe_dropped\x18\n \x01(\x0b\x32\x17.vstimd.v1.FrameDroppedH\x00\x12\x34\n\x0f\x66rame_presented\x18\x0b \x01(\x0b\x32\x19.vstimd.v1.FramePresentedH\x00\x12\x35\n\x10vtl_line_changed\x18\x0c \x01(\x0b\x32\x19.vstimd.v1.VtlLineChangedH\x00\x12\x43\n\x17\x61nimation_state_changed\x18\r \x01(\x0b\x32 .vstimd.v1.AnimationStateChangedH\x00\x12\x32\n\x0eserver_started\x18\x0e \x01(\x0b\x32\x18.vstimd.v1.ServerStartedH\x00\x12\x34\n\x0f\x63ommand_applied\x18\x0f \x01(\x0b\x32\x19.vstimd.v1.CommandAppliedH\x00\x42\t\n\x07payload\"8\n\x0c\x46rameDropped\x12\r\n\x05\x63ount\x18\x02 \x01(\r\x12\x19\n\x11total_since_start\x18\x03 \x01(\x04\"+\n\x0e\x46ramePresented\x12\x19\n\x11since_previous_us\x18\x02 \x01(\r\"~\n\x0eVtlLineChanged\x12\x0c\n\x04\x62\x61nk\x18\x01 \x01(\r\x12\x0b\n\x03\x62it\x18\x04 \x01(\r\x12 \n\x04\x65\x64ge\x18\x02 \x01(\x0e\x32\x12.vstimd.v1.VtlEdge\x12/\n\x04kind\x18\x03 \x01(\x0e\x32!.vstimd.v1.VirtualTriggerLineKind\"\xb2\x01\n\x15\x41nimationStateChanged\x12\x0e\n\x06handle\x18\x01 \x01(\x04\x12\x35\n\x05state\x18\x02 \x01(\x0e\x32&.vstimd.v1.AnimationStateChanged.State\"R\n\x05State\x12\x15\n\x11STATE_UNSPECIFIED\x10\x00\x12\x0f\n\x0bSTATE_ARMED\x10\x01\x12\x11\n\rSTATE_RUNNING\x10\x02\x12\x0e\n\nSTATE_DONE\x10\x03\"`\n\x0e\x43ommandApplied\x12\x0f\n\x07request\x18\x01 \x01(\x0c\x12\x10\n\x08\x61\x63\x63\x65pted\x18\x02 \x01(\x08\x12\x17\n\x0fresponse_handle\x18\x03 \x01(\x05\x12\x12\n\nerror_code\x18\x04 \x01(\x05\"5\n\rServerStarted\x12\x13\n\x0binstance_id\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'vstimd.v1.events_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EVENT']._serialized_start=59
  _globals['_EVENT']._serialized_end=505
  _globals['_FRAMEDROPPED']._serialized_start=507
  _globals['_FRAMEDROPPED']._serialized_end=563
  _globals['_FRAMEPRESENTED']._serialized_start=565
  _globals['_FRAMEPRESENTED']._serialized_end=608
  _globals['_VTLLINECHANGED']._serialized_start=610
  _globals['_VTLLINECHANGED']._serialized_end=736
  _globals['_ANIMATIONSTATECHANGED']._serialized_start=739
  _globals['_ANIMATIONSTATECHANGED']._serialized_end=917
  _globals['_ANIMATIONSTATECHANGED_STATE']._serialized_start=835
  _globals['_ANIMATIONSTATECHANGED_STATE']._serialized_end=917
  _globals['_COMMANDAPPLIED']._serialized_start=919
  _globals['_COMMANDAPPLIED']._serialized_end=1015
  _globals['_SERVERSTARTED']._serialized_start=1017
  _globals['_SERVERSTARTED']._serialized_end=1070
# @@protoc_insertion_point(module_scope)
