# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: vstimd/v1/input.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'vstimd/v1/input.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15vstimd/v1/input.proto\x12\tvstimd.v1\"v\n\rInputAxisInfo\x12\x0c\n\x04name\x18\x01 \x01(\t\x12*\n\x08semantic\x18\x02 \x01(\x0e\x32\x18.vstimd.v1.InputSemantic\x12\r\n\x05scale\x18\x03 \x01(\x02\x12\r\n\x05value\x18\x04 \x01(\x01\x12\r\n\x05\x64\x65lta\x18\x05 \x01(\x01\"\xa6\x01\n\x0fInputDeviceInfo\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07\x62\x61\x63kend\x18\x02 \x01(\t\x12\x11\n\tconnected\x18\x03 \x01(\x08\x12\r\n\x05stale\x18\x04 \x01(\x08\x12\x12\n\ntorn_reads\x18\x05 \x01(\x04\x12&\n\x04\x61xes\x18\x06 \x03(\x0b\x32\x18.vstimd.v1.InputAxisInfo\x12\x16\n\x0estarved_frames\x18\x07 \x01(\x04\"\x19\n\x17ListInputDevicesRequest\"G\n\x18ListInputDevicesResponse\x12+\n\x07\x64\x65vices\x18\x01 \x03(\x0b\x32\x1a.vstimd.v1.InputDeviceInfo*\x84\x01\n\rInputSemantic\x12\x1e\n\x1aINPUT_SEMANTIC_UNSPECIFIED\x10\x00\x12\x1b\n\x17INPUT_SEMANTIC_ABSOLUTE\x10\x01\x12\x1d\n\x19INPUT_SEMANTIC_CUMULATIVE\x10\x02\x12\x17\n\x13INPUT_SEMANTIC_RATE\x10\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'vstimd.v1.input_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INPUTSEMANTIC']._serialized_start=426
  _globals['_INPUTSEMANTIC']._serialized_end=558
  _globals['_INPUTAXISINFO']._serialized_start=36
  _globals['_INPUTAXISINFO']._serialized_end=154
  _globals['_INPUTDEVICEINFO']._serialized_start=157
  _globals['_INPUTDEVICEINFO']._serialized_end=323
  _globals['_LISTINPUTDEVICESREQUEST']._serialized_start=325
  _globals['_LISTINPUTDEVICESREQUEST']._serialized_end=350
  _globals['_LISTINPUTDEVICESRESPONSE']._serialized_start=352
  _globals['_LISTINPUTDEVICESRESPONSE']._serialized_end=423
# @@protoc_insertion_point(module_scope)
