# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: vstimd/v1/scene3d.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'vstimd/v1/scene3d.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from vstimd_client._proto.vstimd.v1 import vec3_pb2 as vstimd_dot_v1_dot_vec3__pb2
from vstimd_client._proto.vstimd.v1 import vtl_pb2 as vstimd_dot_v1_dot_vtl__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17vstimd/v1/scene3d.proto\x12\tvstimd.v1\x1a\x14vstimd/v1/vec3.proto\x1a\x13vstimd/v1/vtl.proto\"\x9a\x01\n\x08\x43\x61mera3D\x12$\n\x0bposition_cm\x18\x01 \x01(\x0b\x32\x0f.vstimd.v1.Vec3\x12\x0f\n\x07yaw_deg\x18\x02 \x01(\x02\x12\x11\n\tpitch_deg\x18\x03 \x01(\x02\x12\x10\n\x08roll_deg\x18\x04 \x01(\x02\x12\x11\n\tfov_y_deg\x18\x05 \x01(\x02\x12\x0f\n\x07near_cm\x18\x06 \x01(\x02\x12\x0e\n\x06\x66\x61r_cm\x18\x07 \x01(\x02\"\x80\x01\n\nLighting3D\x12&\n\rambient_color\x18\x01 \x01(\x0b\x32\x0f.vstimd.v1.Vec3\x12&\n\rsun_direction\x18\x02 \x01(\x0b\x32\x0f.vstimd.v1.Vec3\x12\"\n\tsun_color\x18\x03 \x01(\x0b\x32\x0f.vstimd.v1.Vec3\"7\n\x10SetCameraRequest\x12#\n\x06\x63\x61mera\x18\x01 \x01(\x0b\x32\x13.vstimd.v1.Camera3D\"\x14\n\x12QueryCameraRequest\"=\n\x12SetLightingRequest\x12\'\n\x08lighting\x18\x01 \x01(\x0b\x32\x15.vstimd.v1.Lighting3D\"\x16\n\x14QueryLightingRequest\"\xa5\x02\n\nCameraZone\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x31\n\x04line\x18\x02 \x01(\x0b\x32#.vstimd.v1.VirtualTriggerLineHandle\x12\x15\n\x08x_min_cm\x18\x03 \x01(\x02H\x00\x88\x01\x01\x12\x15\n\x08x_max_cm\x18\x04 \x01(\x02H\x01\x88\x01\x01\x12\x15\n\x08y_min_cm\x18\x05 \x01(\x02H\x02\x88\x01\x01\x12\x15\n\x08y_max_cm\x18\x06 \x01(\x02H\x03\x88\x01\x01\x12\x15\n\x08z_min_cm\x18\x07 \x01(\x02H\x04\x88\x01\x01\x12\x15\n\x08z_max_cm\x18\x08 \x01(\x02H\x05\x88\x01\x01\x42\x0b\n\t_x_min_cmB\x0b\n\t_x_max_cmB\x0b\n\t_y_min_cmB\x0b\n\t_y_max_cmB\x0b\n\t_z_min_cmB\x0b\n\t_z_max_cm\"=\n\x15SetCameraZonesRequest\x12$\n\x05zones\x18\x01 \x03(\x0b\x32\x15.vstimd.v1.CameraZone\"\x18\n\x16ListCameraZonesRequest\"E\n\x0e\x43\x61meraZoneInfo\x12#\n\x04zone\x18\x01 \x01(\x0b\x32\x15.vstimd.v1.CameraZone\x12\x0e\n\x06inside\x18\x02 \x01(\x08\"C\n\x17ListCameraZonesResponse\x12(\n\x05zones\x18\x01 \x03(\x0b\x32\x19.vstimd.v1.CameraZoneInfob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'vstimd.v1.scene3d_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CAMERA3D']._serialized_start=82
  _globals['_CAMERA3D']._serialized_end=236
  _globals['_LIGHTING3D']._serialized_start=239
  _globals['_LIGHTING3D']._serialized_end=367
  _globals['_SETCAMERAREQUEST']._serialized_start=369
  _globals['_SETCAMERAREQUEST']._serialized_end=424
  _globals['_QUERYCAMERAREQUEST']._serialized_start=426
  _globals['_QUERYCAMERAREQUEST']._serialized_end=446
  _globals['_SETLIGHTINGREQUEST']._serialized_start=448
  _globals['_SETLIGHTINGREQUEST']._serialized_end=509
  _globals['_QUERYLIGHTINGREQUEST']._serialized_start=511
  _globals['_QUERYLIGHTINGREQUEST']._serialized_end=533
  _globals['_CAMERAZONE']._serialized_start=536
  _globals['_CAMERAZONE']._serialized_end=829
  _globals['_SETCAMERAZONESREQUEST']._serialized_start=831
  _globals['_SETCAMERAZONESREQUEST']._serialized_end=892
  _globals['_LISTCAMERAZONESREQUEST']._serialized_start=894
  _globals['_LISTCAMERAZONESREQUEST']._serialized_end=918
  _globals['_CAMERAZONEINFO']._serialized_start=920
  _globals['_CAMERAZONEINFO']._serialized_end=989
  _globals['_LISTCAMERAZONESRESPONSE']._serialized_start=991
  _globals['_LISTCAMERAZONESRESPONSE']._serialized_end=1058
# @@protoc_insertion_point(module_scope)
