# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: vstimd/v1/snapshot.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'vstimd/v1/snapshot.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from vstimd_client._proto.vstimd.v1 import animations_pb2 as vstimd_dot_v1_dot_animations__pb2
from vstimd_client._proto.vstimd.v1 import input_pb2 as vstimd_dot_v1_dot_input__pb2
from vstimd_client._proto.vstimd.v1.stimuli import query_pb2 as vstimd_dot_v1_dot_stimuli_dot_query__pb2
from vstimd_client._proto.vstimd.v1 import system_pb2 as vstimd_dot_v1_dot_system__pb2
from vstimd_client._proto.vstimd.v1 import vtl_pb2 as vstimd_dot_v1_dot_vtl__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18vstimd/v1/snapshot.proto\x12\tvstimd.v1\x1a\x1avstimd/v1/animations.proto\x1a\x15vstimd/v1/input.proto\x1a\x1dvstimd/v1/stimuli/query.proto\x1a\x16vstimd/v1/system.proto\x1a\x13vstimd/v1/vtl.proto\"X\n\x0f\x43ommandLogEntry\x12\x0e\n\x06handle\x18\x01 \x01(\r\x12\x0f\n\x07summary\x18\x02 \x01(\t\x12\x0c\n\x04\x63ode\x18\x03 \x01(\x05\x12\x16\n\x0eserver_time_ns\x18\x04 \x01(\x04\"\xca\x03\n\rSceneSnapshot\x12\x37\n\x0bserver_info\x18\x01 \x01(\x0b\x32\".vstimd.v1.QueryServerInfoResponse\x12\x31\n\x07stimuli\x18\x02 \x03(\x0b\x32 .vstimd.v1.QueryStimulusResponse\x12\x35\n\nanimations\x18\x03 \x01(\x0b\x32!.vstimd.v1.ListAnimationsResponse\x12=\n\tvtl_lines\x18\x04 \x01(\x0b\x32*.vstimd.v1.ListVirtualTriggerLinesResponse\x12=\n\tvtl_state\x18\x05 \x01(\x0b\x32*.vstimd.v1.VirtualTriggerLineStateResponse\x12/\n\x0b\x63ommand_log\x18\x06 \x03(\x0b\x32\x1a.vstimd.v1.CommandLogEntry\x12\x13\n\x0b\x66rame_count\x18\x07 \x01(\x04\x12\x16\n\x0eserver_time_ns\x18\x08 \x01(\x04\x12:\n\rinput_devices\x18\t \x01(\x0b\x32#.vstimd.v1.ListInputDevicesResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'vstimd.v1.snapshot_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_COMMANDLOGENTRY']._serialized_start=166
  _globals['_COMMANDLOGENTRY']._serialized_end=254
  _globals['_SCENESNAPSHOT']._serialized_start=257
  _globals['_SCENESNAPSHOT']._serialized_end=715
# @@protoc_insertion_point(module_scope)
