# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: vstimd/v1/transform.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'vstimd/v1/transform.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from vstimd_client._proto.vstimd.v1 import vec2_pb2 as vstimd_dot_v1_dot_vec2__pb2
from vstimd_client._proto.vstimd.v1 import vec3_pb2 as vstimd_dot_v1_dot_vec3__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19vstimd/v1/transform.proto\x12\tvstimd.v1\x1a\x14vstimd/v1/vec2.proto\x1a\x14vstimd/v1/vec3.proto\"D\n\x0bTransform2D\x12\x1f\n\x06pos_px\x18\x01 \x01(\x0b\x32\x0f.vstimd.v1.Vec2\x12\x14\n\x0crotation_deg\x18\x02 \x01(\x02\"z\n\x0bTransform3D\x12$\n\x0bposition_cm\x18\x01 \x01(\x0b\x32\x0f.vstimd.v1.Vec3\x12%\n\x0crotation_deg\x18\x02 \x01(\x0b\x32\x0f.vstimd.v1.Vec3\x12\x1e\n\x05scale\x18\x03 \x01(\x0b\x32\x0f.vstimd.v1.Vec3b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'vstimd.v1.transform_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TRANSFORM2D']._serialized_start=84
  _globals['_TRANSFORM2D']._serialized_end=152
  _globals['_TRANSFORM3D']._serialized_start=154
  _globals['_TRANSFORM3D']._serialized_end=276
# @@protoc_insertion_point(module_scope)
